### ISSUE TITLE
3d support roadmap

### ISSUE THREAD

**Issue by lkeegan** [spatial-model-editor/spatial-model-editor#823]
A work-in-progress list of things required to support 3d models:

- [x] dune-copasi should already support 3d simulation
  - presumably membrane reactions go from a flux across a 1d edge between elements -> flux across the surface of a 2d face between 3-d elements?
- [x] extend Pixel to support 3d (#835)
  - should be straightforward, but simulating might become very slow
- extend GUI to visualize 3d images, geometry, concentration
  - [x] this could just be 2d slices (#836)
  - [x] or maybe some kind of 3d rendering (#923)
- [x] extend GUI to visualize 3d meshes (#882)
- [x] automatic generation of 3d tetrahedral mesh from stack of 2d pixel images / voxel image (#825)
- [x] generate 3d dune tetrahedral mesh  (#881)
- [x] extend SBML support to include 3d models
  - need to ensure consistency between 2d & 3d models
- [ ] (optional) add support for SBML export to mesh geometry (#952)
- [ ] (optional) add support for SBML import from mesh geometry (#951)

**Comment by SoilRos** [comment]
> * dune-copasi should already support 3d simulation
>   * presumably membrane reactions go from a flux across a 1d edge between elements -> flux across the surface of a 2d face between 3-d elements?

I assume you mean the transmission conditions. If so, yes. It just happens at the intersection between two entities of the world dimension.
